### ISSUE TITLE
thread problem when runing on device

### ISSUE THREAD

**Issue by holbalzs** [JonasGessner/JGProgressHUD#120] opened 2019-09-06 12:02 UTC
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 350, TID: 16165, Thread name: com.apple.CoreMotion.MotionThread, Queue name: com.apple.root.default-qos.overcommit, QoS: 0

**Comment by JonasGessner** [comment] 2019-09-06 12:14
Dupe of #98.

**Closed by JonasGessner** 2019-09-06 12:14 UTC
