### ISSUE TITLE
iOS 12.1.4 (or iPhone XR?) causing Main Thread Checker errors

### ISSUE THREAD

**Issue by jbmaxwell** [JonasGessner/JGProgressHUD#110] opened 2019-03-12 15:45 UTC
I'm getting a Main Thread Checker error when showing the HUD. I actually moved over from PKHUD for the same reason, so I'm guessing this must be due to some significant changes to iOS (on the PKHUD git there are issues also relating to iPhone X/XR).

```
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 4738, TID: 960094, Thread name: com.apple.CoreMotion.MotionThread, Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   libobjc.A.dylib                     0x00000001a015b534 <redacted> + 56
5   CoreMotion                          0x00000001a69e4040 CoreMotion + 307264
6   CoreMotion                          0x00000001a69e4574 CoreMotion + 308596
7   CoreMotion                          0x00000001a69e4484 CoreMotion + 308356
8   CoreMotion                          0x00000001a6a15c64 CoreMotion + 511076
9   CoreMotion                          0x00000001a6a15cc4 CoreMotion + 511172
10  CoreFoundation                      0x00000001a0ef4354 <redacted> + 28
11  CoreFoundation                      0x00000001a0ef3c38 <redacted> + 276
12  CoreFoundation                      0x00000001a0eeef14 <redacted> + 2324
13  CoreFoundation                      0x00000001a0eee2e8 CFRunLoopRunSpecific + 452
14  CoreFoundation                      0x00000001a0eef04c CFRunLoopRun + 84
15  CoreMotion                          0x00000001a6a155fc CoreMotion + 509436
16  libsystem_pthread.dylib             0x00000001a0b68974 <redacted> + 132
17  libsystem_pthread.dylib             0x00000001a0b688d0 _pthread_start + 52
18  libsystem_pthread.dylib             0x00000001a0b70ddc thread_start + 4
2019-03-12 08:42:18.240910-0700 Spliqs[4738:960094] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 4738, TID: 960094, Thread name: com.apple.CoreMotion.MotionThread, Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   libobjc.A.dylib                     0x00000001a015b534 <redacted> + 56
5   CoreMotion                          0x00000001a69e4040 CoreMotion + 307264
6   CoreMotion                          0x00000001a69e4574 CoreMotion + 308596
7   CoreMotion                          0x00000001a69e4484 CoreMotion + 308356
8   CoreMotion                          0x00000001a6a15c64 CoreMotion + 511076
9   CoreMotion                          0x00000001a6a15cc4 CoreMotion + 511172
10  CoreFoundation                      0x00000001a0ef4354 <redacted> + 28
11  CoreFoundation                      0x00000001a0ef3c38 <redacted> + 276
12  CoreFoundation                      0x00000001a0eeef14 <redacted> + 2324
13  CoreFoundation                      0x00000001a0eee2e8 CFRunLoopRunSpecific + 452
14  CoreFoundation                      0x00000001a0eef04c CFRunLoopRun + 84
15  CoreMotion                          0x00000001a6a155fc CoreMotion + 509436
16  libsystem_pthread.dylib             0x00000001a0b68974 <redacted> + 132
17  libsystem_pthread.dylib             0x00000001a0b688d0 _pthread_start + 52
18  libsystem_pthread.dylib             0x00000001a0b70ddc thread_start + 4
```

**Comment by cosmicsalad** [comment] 2019-03-12 22:53
Looks like unfortunately this is a known bug with 2018 iPhones that's been submitted to Apple: https://openradar.appspot.com/46210367

**Comment by JonasGessner** [comment] 2019-04-02 18:48
Dupe of #98.

**Closed by JonasGessner** 2019-04-02 18:48 UTC
