### ISSUE TITLE
Auto Light or Dark Mode

### ISSUE THREAD

**Issue by thejeff77** [JonasGessner/JGProgressHUD#129] opened 2019-11-06 01:55 UTC
I'll just leave this here, I figure there is an ObjC equivalent. Helps cut down on code for iOS 13 w/ dark mode in most situations.

```
import Foundation
import JGProgressHUD

extension JGProgressHUD {
    convenience init(forVC vc: UIViewController) {
        if #available(iOS 13, *) {
            if (vc.traitCollection.userInterfaceStyle == .dark) {
                self.init(style: .light)
            }
            else {
                self.init(style: .dark)
            }
        } else {
            self.init(style: .dark)
        }
    }
}
```
Usage: 
`let hud = JGProgressHUD(forVC: self)`

**Comment by JonasGessner** [comment] 2019-12-06 10:44
Dupe of #122.

**Closed by JonasGessner** 2019-12-06 10:44 UTC
